### ISSUE TITLE
Leaked variable from list comprehension in method extraction.

### ISSUE THREAD

**Issue by Ferada** [python-rope/rope#102]
I've come across some unexpected behaviour while extracting a method, although I'm not sure if it's not still technically correct.

A reduce example is something like the following:

    def foo():
        x = [e for e in []]

        for e in []:
            def bar():
                e[42] = 1

Marking the complete loop body and running method extraction will produce the following result:

    def foo():
        x = [e for e in []]

        baz(e)

    def baz(e):
        for e in []:
            def bar():
                e[42] = 1

What is unexpected is the `e` parameter for `baz`.  If the `x = ...` is removed, that parameter isn't added, so it looks to me like it's including the leaking variable from the list comprehension (something
you can also stumble upon in general), although the `e` from the `for`-loop will definitely supersede it.

**Comment by mcepl** [comment]
@aligrudi what do you think? It truly looks like a bug to me.

**Comment by aligrudi** [comment]
Matěj Cepl <notifications@github.com> wrote:
> @aligrudi what do you think? It truly looks like a bug to me.

Indeed.  To fix it, the _For() method of _FunctionInformationCollector
in rope/refactor/extract.py has to be modified.  I wonder why
node.target does not have a Name node with ast.Store context.

	Ali
