### ISSUE TITLE
failing tests on Windows

### ISSUE THREAD

**Issue by mcepl** [python-rope/rope#106]
See https://gitlab.com/mcepl/rope/snippets/3192 for the full log.

Some issues are clearly Windows weirdness (e.g., subprocess), but some are looking as rope lacks some stability of the code (e.g., `<rope.base.pyobjectsdef.PyClass object at 0x02981870> != <rope.base.pyobjectsdef.PyClass object at 0x029B4930>`)

**Comment by aligrudi** [comment]
> See https://gitlab.com/mcepl/rope/snippets/3192 for the full log.
> 
> Some issues are clearly Windows weirdness (e.g., subprocess), but some are looking as rope lacks some stability of the code (e.g., `<rope.base.pyobjectsdef.PyClass object at 0x02981870> != <rope.base.pyobjectsdef.PyClass object at 0x029B4930>`)

The main problem seems to be in DynamicOITest; rope needs to execute
python modules in a sub-process to collect the type of objects passed
to functions.  This seems to fail: either rope fails to start the
sub-process or it cannot receive the information the process sends
back.  Instead of fixing it, it may be acceptable to add a test
decorator (@onlyunix for instance) to disable them on Windows.

	Ali

**Comment by mcepl** [comment]
I played with it for a moment and I am returning to the `run` method in `doa.py` module.

1. When running on Linux v. Windows, the args variable is very different. On Windows it is
```
['C:\\Python27\\python.exe', 'C:\\Users\\ceplm\\D...t\\mod.py']
```
(yes, I hope the string is actually complete, just Visual Studio is not willing to give me better representation), whereas on Linux it is
```
['/usr/bin/python',
 '/home/matej/archiv/knihovna/repos/rope/rope/base/oi/runmod.py',
 '3037',
 '/dev/shm/sample_project',
 '/dev/shm/sample_project/mod.py']
```
(yes, Eclipse provides a way more civilized output)
It seems like we run completely different Python script, and also all remaining parameters are missing. 
2. What is `executable` parameter of `subprocess.Popen` good for?
3. both `stdout` and `stderr` parameters point to the same file `sys.stdout`. Is it correct? Do we need `stderr` at all? Or shouldn't we collect their content to two variables and combine them later if necessary?

**Comment by mcepl** [comment]
> Instead of fixing it, it may be acceptable to add a test decorator (@onlyunix for instance) to disable them on Windows.

We already have `ropetest.testutils.run_only_for_unix`. When we finally have `unittest2` (or `unittest` if python >= 2.7), shouldn't we use proper `unittest.skip` decorators? E.g., documentation shows this as an example:
```python
def skipUnlessHasattr(obj, attr):
    if hasattr(obj, attr):
        return lambda func: func
    return unittest.skip("{!r} doesn't have {!r}".format(obj, attr))
```

**Comment by mcepl** [comment]
When I run this test on Windows just in plain Python `pdb` I got
```python
args = ['C:\\Python27\\python.exe',
 'C:\\Users\\ceplm\\Source\\Repos\\rope\\rope\\base\\oi\\runmod.py
 '-',
 'C:\\Users\\ceplm\\Source\\Repos\\rope\\sample_project',
 'C:\\Users\\ceplm\\Source\\Repos\\rope\\sample_project\\mod.py']
``
Curiouser and curiouser!

**Comment by mcepl** [comment]
With pull request #108 all tests pass on Windows when run via `python setup.py test` (Visual Studio is somehow broken, but I don't think it matters).

**Comment by soupytwist** [comment]
This seems to be resolved, closing.
