### ISSUE TITLE
Consider fixes from python-mode

### ISSUE THREAD

**Issue by mcepl** [python-rope/rope#109]
Not that it make much sense to me, but we have
- [ ] https://github.com/klen/python-mode/commit/cec42722bf3f217da1ffbaa5c0486e3dfb08a377
- [x] https://github.com/klen/python-mode/commit/70d8eab3bee42fbde292b4fa2813e69d9a5e45fe

**Comment by aligrudi** [comment]
Matěj Cepl <notifications@github.com> wrote:
> Not that it make much sense to me, but we have
>  * [ ] https://github.com/klen/python-mode/commit/cec42722bf3f217da1ffbaa5c0486e3dfb08a377

This seems OK.

>  * [ ] https://github.com/klen/python-mode/commit/70d8eab3bee42fbde292b4fa2813e69d9a5e45fe

I am not sure about this one:

> diff --git a/pylibs/rope/base/pycore.py b/pylibs/rope/base/pycore.py
> --- a/pylibs/rope/base/pycore.py
> +++ b/pylibs/rope/base/pycore.py
> @@ -306,7 +305,7 @@ def __init__(self, pycore):
>  
>      def _invalidate_resource(self, resource):
>          if resource in self.module_map:
> -            self.forget_all_data()
> +            self.module_map[resource]._forget_concluded_data()
>              self.observer.remove_resource(resource)
>              del self.module_map[resource]

I think self.forget_all_data() cannot be removed: if "resource"
is imported in other modules, they need to be invalidated as well.

> @@ -258,7 +258,6 @@ def analyze_module(self, resource, should_analyze=lambda py: True,
>          if followed_calls is None:
>              followed_calls = self.project.prefs.get('soa_followed_calls', 0)
>          pymodule = self.resource_to_pyobject(resource)
> -        self.module_cache.forget_all_data()
>          rope.base.oi.soa.analyze_module(
>              self, pymodule, should_analyze, search_subscopes, followed_calls)

I am not sure about this one; I guess forget_all_data() is called
to invalidate cached PyObjects, before starting static object
analysis.

	Ali

**Comment by mcepl** [comment]
> > Not that it make much sense to me, but we have * [ ] https://github.com/klen/python-mode/commit/cec42722bf3f217da1ffbaa5c0486e3dfb08a377
> This seems OK.

If we are talking just about https://github.com/klen/python-mode/commit/cec42722bf3f217da1ffbaa5c0486e3dfb08a377#diff-8b16a9732c18882bc9cb97b31ec63e28R370 (i.e., adding `path = path or ''`) isn't better to make a formal parameter path optional defaulting to ""?

> * [ ] https://github.com/klen/python-mode/commit/70d8eab3bee42fbde292b4fa2813e69d9a5e45fe

OK, let's forget about this one.

**Comment by aligrudi** [comment]
Matěj Cepl <notifications@github.com> wrote:
> > > Not that it make much sense to me, but we have * [ ] https://github.com/klen/python-mode/commit/cec42722bf3f217da1ffbaa5c0486e3dfb08a377
> > This seems OK.
> 
> If we are talking just about https://github.com/klen/python-mode/commit/cec42722bf3f217da1ffbaa5c0486e3dfb08a377#diff-8b16a9732c18882bc9cb97b31ec63e28R370 (i.e., adding `path = path or ''`) isn't better to make a formal parameter path optional defaulting to ""?

Indeed.  I wonder why should anyone pass None to _realpath()?
Does it ever happen?  If it does, I think the caller needs to
be fixed, instead of changing _realpath().

	Ali

**Comment by lieryan** [comment]
Closing. Considering the conversation, I think all issues here have already been considered.
