### ISSUE TITLE
Unexpected behavior when extracting loop body

### ISSUE THREAD

**Issue by NicolasWebDev** [python-rope/rope#112]
Program versions:
- rope==0.10.2
- ropemode==0.2
- ropevim==0.5.0

Let's say I have the following function:

``` python
def my_func():
    i = 0
    for dummy in range(10):
        i += 1
        print i
```

When I select the i += 1 for method extraction, I get:

``` python
def my_func():
    i = 0
    for dummy in range(10):
        i = increment(i)
        print i

def increment(i):
    i += 1
    return i
```

which is exactly what I would expect.

But if I extractmethod all of the loop body instead, I get:

``` python
def my_func():
    i = 0
    for dummy in range(10):
        increment_and_print(i)

def increment_and_print(i):
    i += 1
    print i
```

which clearly gives me a different output.

It seems that variables that are used inside the body are not detected as necessary return values, which may lead to erratic behavior and bugs (which will be hard to track down).

If this is known because too difficult to implement, then I think it would be really nice to have a list of the Rope known limitations, so as to know its weaknesses.

Thanks.

**Comment by aligrudi** [comment]
Sathors <notifications@github.com> wrote:
> Let's say I have the following function:
> ```python
> def my_func():
>     i = 0
>     for dummy in range(10):
>         i += 1
>         print i
> ```
> 
> But if I extractmethod all of the loop body instead, I get:
> ```python
> def my_func():
>     i = 0
>     for dummy in range(10):
>         increment_and_print(i)
> 
> def increment_and_print(i):
>     i += 1
>     print i
> ```
> which clearly gives me a different output.
> 
> It seems that variables that are used inside the body are not detected as necessary return values, which may lead to erratic behavior and bugs (which will be hard to track down).

It should not be difficult to fix (and may be introduced in
the last series of changes to inline.py).

	Ali
