### ISSUE TITLE
Problem in ExtractMethod when incrementing a variable.

### ISSUE THREAD

**Issue by NicolasWebDev** [python-rope/rope#114]
Let's say I have the following code:

``` python
i = 1
i += 1
print(i)
```

It prints two.

When extracting the second line, I would expect:

``` python
i = 1

def extracted(i)
    return i + 1

i = extracted(i)
print(i)
```

I get instead:

``` python
i = 1

def test():
    i += 1
    return i

i = test()
print(i)
```

which clearly does not work.

I know nothing about the complexity of managing assignment operators, but if it is not supported at the moment, it would be better to block the refactoring instead of creating a wrong one.

Thanks for your help.

**Comment by aligrudi** [comment]
Sathors <notifications@github.com> wrote:
> Let's say I have the following code:
> ```python
> i = 1
> i += 1
> print(i)
> ```
> It prints two.
> 
> When extracting the second line, I would expect:
> ```python
> i = 1
> 
> def extracted(i)
>     return i + 1
> 
> i = extracted(i)
> print(i)
> ```
> 
> I get instead:
> ```python
> i = 1
> 
> def test():
>     i += 1
>     return i
> 
> i = test()
> print(i)
> ```
> 
> which clearly does not work.

Is this caused by the recent changes to rope/refactor/extract.py?

	Ali

**Comment by lieryan** [comment]
Your proposed refactoring is not a safe refactoring. Inline assignment calls `__iadd__` which may implement something completely different than the `__add__` method for non-builtin types.

The safe alternative would be to pass `i` as a parameter:

```
i = 1

def extracted(i):
    i += 1
    return i

i = extracted(i)
print(i)
```

or turn it into `global`:

```
i = 1

def extracted():
    global i
    i += 1

extracted()
print(i)
```
The first alternative is more universal, as it will also work when `i` is not in the global scope.
