### ISSUE TITLE
Support Cython

### ISSUE THREAD

**Issue by elvis-sik** [python-rope/rope#123]
PyCharm can refactor Cython code. I don't expect myself to use this, anyway. Is it realistic to do it within rope, or it would be wiser to make a new library? (and if so, would it be a daunting task?).

**Comment by mcepl** [comment]
I have absolutely no idea. I guess it would require parsing of the Cython source and generating AST trees (is there something like that prepared?). Then you can start trying to fiddle with such tree via rope. It seems like quite a task.

@aligrudi what do you think?

**Comment by aligrudi** [comment]
Matěj Cepl <notifications@github.com> wrote:
> I have absolutely no idea. I guess it would require parsing of the Cython source and generating AST trees (is there something like that prepared?). Then you can start trying to fiddle with such tree via rope. It seems like quite a task.
> 
> @aligrudi what do you think? 

I am afraid that is not possible in rope, due to the
differences in ASTs between Python and Cython.

	Ali
