### ISSUE TITLE
Tutorial?

### ISSUE THREAD

**Issue by julj** [python-rope/rope#125]
I just installed python-rope and I cannot find anywhere how to use it! I read the Rope Overview but I don't know how to start.

1 - sudo apt-get install python-rope
2 - ?

How/when .ropeproject is created? How to rename a module (so that all the call to this module are renamed too) for instance?

**Comment by aligrudi** [comment]
Julien Ricard <notifications@github.com> wrote:
> I just installed python-rope and I cannot find anywhere how to use it! I read the Rope Overview but I don't know how to start.
> 
> 1 - sudo apt-get install python-rope
> 2 - ?
> 
> How/when .ropeproject is created? How to rename a module (so that all the call to this module are renamed too) for instance?

I guess python-rope installs the library only, so you can use
its API, as explained in library.txt.  However, if you plan to
use rope inside an editor, you need a plug-in like ropevim
(for Vim) or ropemacs (for Emacs).

	Ali
