### ISSUE TITLE
Don’t convert from CRLF to LF

### ISSUE THREAD

**Issue by mcepl** [python-rope/rope#134]
Reproduction steps:
1. edit a Python script with CRLF as EOLs in vim
2. make any operation on it (e.g., variable rename)

Observed:

The file has LF as EOL now.

Expected:

Don't do anything else than asked for.

**Comment by DonJayamanne** [comment]
Any idea why this is being done in the library? Why concert crlf to lf, send completely silly and wrong..

**Comment by soupytwist** [comment]
One reason it probably does this now is that when rope adds new lines, it always adds unix line endings, so assuming unix line endings makes this job a lot easier. I think part of fixing this is going to require detecting and using the correct line endings for a given file (which is reasonable).

For example:
https://github.com/python-rope/rope/blob/c9a52b068321d882447d78ea376f2efd93f085e0/rope/refactor/importutils/module_imports.py#L474
