### ISSUE TITLE
Moving content from file A to file B and then updating A

### ISSUE THREAD

**Issue by shackra** [python-rope/rope#136]
Hello!

I'm not sure if this exists on rope. I want to move some definitions of variables from one file to another. Thing is, these variables are heavily used on the first file which means that an update by hand will be required after moving them.

I thought this would be a job for a computer and not a human, *The computer should be doing the hard work. That's what it's paid to do, after all.*

**Comment by mcepl** [comment]
I don't understand the problem. You move definition of ``foo`` to other module ``bar`` and then you include into the first module ``from bar import foo``. What else is to do for the computer?

**Comment by shackra** [comment]
Oh, if you put it that way I guess nothing! 😅

El 11 de enero de 2016 03:03:18 CST, "Matěj Cepl" <notifications@github.com> escribió:
>I don't understand the problem. You move definition of ``foo`` to other
>module ``bar`` and then you include into the first module ``from bar
>import foo``. What else is to do for the computer?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/python-rope/rope/issues/136#issuecomment-170474203

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mcepl** [comment]
> Oh, if you put it that way I guess nothing! 😅

I mean really I didn’t want to shut you down. I just really didn't know what you were talking about so I tried to get some more explanation from you.

**Comment by shackra** [comment]
No, no, it's fine! 

I totally forget that importing the object instead of just the module would save me from putting the module in front of the object in everywhere I used such object in my file! 

El 11 de enero de 2016 11:45:02 CST, "Matěj Cepl" <notifications@github.com> escribió:
>> Oh, if you put it that way I guess nothing! 😅
>
>I mean really I didn’t want to shut you down. I just really didn't know
>what you were talking about so I tried to get some more explanation
>from you.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/python-rope/rope/issues/136#issuecomment-170630285

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mcepl** [comment]
OK, thanks for being of help.
