### ISSUE TITLE
Make pluggable providers for type hinting

### ISSUE THREAD

**Issue by emacsway** [python-rope/rope#150]

**Comment by emacsway** [comment]
@soupytwist , assign to me, please

**Comment by emacsway** [comment]
Done!
@soupytwist , please, merge #187

**Comment by mcepl** [comment]
OK, is there some piece of documentation what all this means? Could it be somehow used by the plugin writers (e.g., ``ropemacs`` and ``ropevim``)?

**Comment by emacsway** [comment]
@mcepl , it's a good idea. First of all, the pluggable providers required by #146. I need it to go forward. I've added ticket #191 to add docs how to write pluggable type-hinting providers.
