### ISSUE TITLE
not extract for ... else 

### ISSUE THREAD

**Issue by MarekLew** [python-rope/rope#155]
rope do not extract function from **for .... else** statemant

extract:
```
def a_func():
    for i in range(10):
        a=i
    else:
        a=None
```
to:
```
def a_func():
    new_func()

def new_func():
    for i in range(10):
        a=i
    else:
        a=None
```

commit where I **add test**:
https://github.com/MarekLew/rope/commit/3e6155a5f82be1d6c99597eed0a9f730629ce388

**Comment by MarekLew** [comment]
https://github.com/python-rope/rope/pull/156 fix it

**Comment by mcepl** [comment]
Merged.
