### ISSUE TITLE
TabError: inconsistent use of tabs and spaces in indentation

### ISSUE THREAD

**Issue by ColinDuquesnoy** [python-rope/rope#163]
Hello,

I've tried to install rope from master branch, but it failed with the following error:

```python
Obtaining rope from git+git://github.com/python-rope/rope.git@master#egg=rope (from -r requirements-dev.txt (line 2))
  Updating ./src/rope clone (to master)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/colin/Documents/hackedit-python/src/rope/setup.py", line 10, in <module>
        import ropetest
      File "/home/colin/Documents/hackedit-python/src/rope/ropetest/__init__.py", line 21, in <module>
        import ropetest.refactor
      File "/home/colin/Documents/hackedit-python/src/rope/ropetest/refactor/__init__.py", line 8, in <module>
        import ropetest.refactor.extracttest
      File "/home/colin/Documents/hackedit-python/src/rope/ropetest/refactor/extracttest.py", line 994
        code = 'def a_func():\n    for i in range(10):\n        a = i\n    else:\n        a=None\n'
                                                                                                  ^
    TabError: inconsistent use of tabs and spaces in indentation
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /home/colin/Documents/hackedit-python/src/rope/

```

**Comment by mcepl** [comment]
Good person committing 7232b26878c76040865358190f925e4c6be15e8d broke our code.

**Comment by ColinDuquesnoy** [comment]
Thank you!

**Comment by MarekLew** [comment]
Sorry about that.  7232b26 is my first fix. Unfortunately, I relied solely on testing and installing "python setup.py install".

**Comment by MarekLew** [comment]
Yes It's happens
I tested this on two computers and 3 systems before committing. 
On Ubuntu (14.04,14.06) and python 2.7.12 all test passed. 
On windows 7 more test fault(I don't care this.). 
Changing editor helped ;)

**Comment by kaoutharl** [comment]
obviously i am a bit late, but i'm training to run a program (python 2.7) on windows 10 and i get a indentation error. although i'm using the exact same code on ubuntu and it is running perfectly.. does 
 same code on ubuntu and it is running perfectly.. how can I fix it??

**Comment by soupytwist** [comment]
This issue was not windows-specific, so probably not the right forum.

Using spaces instead of tabs might help clear up your problem.
