### ISSUE TITLE
Not working in Python 3

### ISSUE THREAD

**Issue by DonJayamanne** [python-rope/rope#167]
I'm trying to use this library in Python3, however it falls over with the following errors.
FYI - I can see the the same errors are reported on CI Travis (for Python 3 https://travis-ci.org/search/python-rope)
```
Traceback (most recent call last):
  File "...rope/base/project.py", line 230, in __init__
    self._init_prefs(prefs)
  File "...rope/base/project.py", line 272, in _init_prefs
    execfile(config.real_path, run_globals)
TypeError: execfile() missing 1 required positional argument: 'local_vars'
```

Rope Version 10.3
Python Version 3.5

**Comment by mcepl** [comment]
Yes, it is not. There are some efforts in [devel branch](https://github.com/python-rope/rope/tree/devel) to port rope to python 3, but it has not been finished yet. More work on that branch is definitively welcome.

**Comment by DonJayamanne** [comment]
Oh, I thought I was already supported thanks. Will check out the code.
