### ISSUE TITLE
Question: Contributing to the devel brach for Python 3.5

### ISSUE THREAD

**Issue by DonJayamanne** [python-rope/rope#171]
@mcepl, I'm in the process of trying to resolve the issues in rope library when running under Python 3.5.
So far I've made two PRs.
Over the next few weeks/months, more issues will be fixed (that's the intent), hence more PRs will be submitted. 

I'm going to assume that most of the future fixes will rely on older fixes that I may have made. for instance the PR #169 is crucial to getting #170 working. However if I keep adding all the changes to the same PR it could get quite complicated for you to review the changes.

Let me know what you prefer.
- Keep updating the original PR #169 with new fixes (feels like the best solution in my opinion). However when you start reviewing you could have a who lot of files, and it would be best if you inform me when you start reviewing, so I can pause submitting more changes to the same PR)
- Create news PRs for each fix (however fixes from previous PRs will have to be added into them to ensure unit tests pass). This approach feels too complicated, but you'll have fewer changes to review.
- Or any other

**Comment by mcepl** [comment]
http://thread.gmane.org/gmane.comp.python.rope/704

**Comment by alflanagan** [comment]
@soupytwist is the new maintainer for rope: https://www.mail-archive.com/rope-dev@googlegroups.com/msg00002.html

gmane.org is down, maybe permanently: https://lars.ingebrigtsen.no/2016/07/28/the-end-of-gmane/comment-page-1/#comment-13502. Clearly maintaining volunteer support for these projects is tough. At least @mcepl hasn't been sued (I hope).

Thanks @mcepl for all your work.

**Comment by soupytwist** [comment]
Hi @DonJayamanne,

I'm not sure where this was left off-- did you decide on a strategy to move forward with this? Personally, I prefer smaller PRs + rebasing as it makes reviews + debugging issues a lot simpler. I'll take a look at your existing pulls very soon as I catch up with the state of this repo. If you can keep your changes small, I can review them quickly and hopefully we won't waste too much time.

Thanks,
Nick

**Comment by DonJayamanne** [comment]
Hi Nick,

I will resubmit the PR today as I have merged the matter into my revel branch. Yes they are small do it should be ok.

Cheers,
Don

Get Outlook for iOS<https://aka.ms/o0ukef>

_____________________________

**Comment by DonJayamanne** [comment]
@soupytwist , here's the new PR #172

**Comment by DonJayamanne** [comment]
Finally, @soupytwist now, that we have a new maintainer for this repo, i believe this issue can be closed.

**Comment by soupytwist** [comment]
Thank you for the updates, I'll take a look at your pulls tonight.

**Comment by DonJayamanne** [comment]
@soupytwist , with the new PR all the unit tests pass except for pypy (plenty of changes/fixes left there). Does this mean this devel branch can now be merged into the master. 
FYI - I have deployed the devel branch (after merging the master into it) with [my product](https://github.com/DonJayamanne/pythonVSCode).

**Comment by soupytwist** [comment]
I'm not quite familiar enough with what's been going on in the devel branch to be comfortable merging it yet-- perhaps soon, if the tests are looking good. I'm not quite sure what @mcepl had intended for when to merge this branch.

**Comment by emacsway** [comment]
Hi, @soupytwist ,

First of all, let me say Thank you for decision to maintain rope. And thank to all contributors who involved in rope development.

The devel branch does not support fully Python3 (there is left a lot of work), but it passes all tests.
Some part of the branch was done by me. Another part was done (and finished) by @sergeyglazyrindev

I suggest merge it, so all commits in master will be python3 compatible.

**Comment by soupytwist** [comment]
Thanks @emacsway. I created #173 to track this, in case there are any problems. I'll take another look through the branch asap and merge if it is ok.

**Comment by emacsway** [comment]
Thank you,  @soupytwist

**Comment by DonJayamanne** [comment]
```devel branch does not support fully Python3 (there is left a lot of work)```
@emacsway , please could you elaborate on this. For instance what isn't supported, we could possibly try adding the unit tests or keep track of what needs to be supported/fixed for python3.
I'd like to try an pitch in to help.

**Comment by emacsway** [comment]
@DonJayamanne , yes, sure.
