### ISSUE TITLE
RopeRestructure bug

### ISSUE THREAD

**Issue by mckelvin** [python-rope/rope#175]
I'm using the python-rope/ropevim vim plugin and find a bug:

pattern: `assert_true(${param})`
goal: `assert ${param}`

input: `assert_true(abs(lower[i + 0] - 87.7086) < 1e-3)`
unexpected output: `assert abs(lower[i + 0] - 87.7086) < 1e`

the output should be `assert abs(lower[i + 0] - 87.7086) < 1e-3`

* * *

Update: another similar bad case

pattern: `assert_equals(${param1}, ${param2})`
goal: `assert ${param1} == ${param2}`

input: `assert_equals(r, -100)`
unexpect output: `assert r == 100`

the output should be `assert r == -100`

**Comment by soupytwist** [comment]
Thanks for reporting this. That is strange, I'll see if I can track down what's causing it as soon as I get some time.

**Comment by soupytwist** [comment]
Unfortunately this was a bug in some [re parsing](https://xkcd.com/1171/) and should be fixed by b1a7fe5035b41602717fb58996ac53f66445954d. It can use some more attention still, but should be improved. Please let me know if there is still a problem.

Thank you again!

**Comment by mckelvin** [comment]
@soupytwist 👏  Thanks so much.
