### ISSUE TITLE
patchedast test coverage is insufficient

### ISSUE THREAD

**Issue by soupytwist** [python-rope/rope#176]
There are cases where `patchedast.patch_ast` fails with "cannot be matched" errors. I have not narrowed this down to specific cases that fail yet, this needs to be investigated so these can be fixed and tests written.

**Comment by lieryan** [comment]
Closing this ticket because there isn't sufficient information here to investigate the problem. If anyone can provide more info about this issue, please either add to the ticket or create a new ticket.
