### ISSUE TITLE
definition not found error while found definition in library.

### ISSUE THREAD

**Issue by hackrole** [python-rope/rope#188]
currently, the rope_goto_definition works on names defined in my project code. while I want to jump to a name defined in the library(for example rest_framework.viewsets.ModelViewset), it gives error message. Definition not found.
![ba0b65e2-955b-11e6-85b7-e6e72bb069e1](https://cloud.githubusercontent.com/assets/2100811/19886213/4185ae86-a05d-11e6-8d96-95a0792e5a2b.png)

**Comment by mcepl** [comment]
Is the library already imported in the current file?

**Comment by hackrole** [comment]
yes, I import it and then try to find the definition on it definitions.

**Comment by emacsway** [comment]
@hackrole , do you use virtualenv? Are your editor running in this virtualenv or has activated it?

**Comment by hackrole** [comment]
yes, I use virtualenv and virtualenv-wrapper. I use virtualenv-vim plugin. And I am sure I have active it on my vim, use 
`:virtualEnvActive tms`

**Comment by mcepl** [comment]
OK, no clue about ``virtualenv``, I don't use it.

**Comment by emacsway** [comment]
I'm not a vim user, so, have a limited possibilities to hep. But I think, you need debug [sys.path](https://docs.python.org/2/library/sys.html#sys.path), for example by logging.debug(), to be sure, your library path is present in it.

**Comment by emacsway** [comment]
As I see on latest screen shot, you try go to definition of module. Go to definition currently does not work for modules.

On last by one screen shot you try to go to definition of C function, it also does not work currently (watch for #148)

**Comment by hackrole** [comment]
That was sad to me. Hope the new version can do more things.
