### ISSUE TITLE
import reordering breaks import cycle mitigation

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [python-rope/rope#195]
while moving a package around using a script with rope, rope moved one of my import statements from the end of a module to the start of a module,

however this import statement was placed intentionally there to work around a import cycle

an illustrative example `__init__.py`

```
import oldmod
class Base(oldmod.MagicObject):
   ...

from . import others
```
gets turned into 

```
import newmod

from . import others
class Base(newmod.MagicObject):
   ...

```

**Comment by soupytwist** [comment]
Hi,
I have added an option a few months ago to address this issue, specifically. Can you please try setting this [configuration variable](https://github.com/python-rope/rope/blob/master/rope/base/default_config.py#L94) for your project:

`pull_imports_to_top=False`

This should prevent the issue you're having. Please let me know if this works for you.

**Comment by RonnyPfannschmidt** [comment]
experimenting with it now, this may also be the cause of #196

**Comment by RonnyPfannschmidt** [comment]
this one happens even with pull_imports_to_top in config.py

**Comment by soupytwist** [comment]
Thanks for the info. What version of rope are you using?

**Comment by RonnyPfannschmidt** [comment]
`rope==0.10.3` pip installed

**Comment by soupytwist** [comment]
Okay, this release is very old compared to HEAD-- pypy is very outdated unfortunately. This fix isn't contained in a release yet.

@mcepl, I think I need your help to update the package in pypy.

**Comment by RonnyPfannschmidt** [comment]
this one is not happening on master, thanks 👍

**Comment by mcepl** [comment]
> @mcepl, I think I need your help to update the package in pypy.

What's you id on PyPI? I can fix it here then https://pypi.python.org/pypi?:action=role_form&package_name=rope
