### ISSUE TITLE
add helpfull __repr__

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [python-rope/rope#197]
when coding interactively with rope in ipython or pdb on a fixup script its quite a pain to discover each object in detail

it would be very nice/helpful if the __repr__ was more detailed for paths/modules/anything else that makes sense

**Comment by lieryan** [comment]
We'll need help here from rope user community that uses rope interactively in CLI to help figure out an API that would work for you when you're using rope in this way. 

For the moment, I'm closing this ticket as this ticket is not really actionable in its current form. But I will accept submissions to implement this, if anyone wanted to draft a proposal for what this `__repr__` interface should look like. I'd suggest either creating a PR implementing your proposed solution or opening a thread in GitHub Discussion to make your proposals.
