### ISSUE TITLE
Test failures on python2

### ISSUE THREAD

**Issue by stratakis** [python-rope/rope#211]
When invoking 'python setup.py test' under Python 2.7.13 on a Fedora 25 machine, two tests are failing:

The issues do not appear when invoking the tests with python3.

FAIL: test_time_in_std_mods (ropetest.builtinstest.BuiltinModulesTest)
Traceback (most recent call last):
  File "/home/<snip>/fedora-scm/python-rope/rope-0.10.5/ropetest/builtinstest.py", line 503, in test_time_in_std_mods
    self.assertTrue('time' in rope.base.stdmods.standard_modules())
AssertionError: False is not true

FAIL: test_sorting_imports_and_standard_modules2 (ropetest.refactor.importutilstest.ImportUtilsTest)
Traceback (most recent call last):
  File "/home/<snip>/fedora-scm/python-rope/rope-0.10.5/ropetest/refactor/importutilstest.py", line 814, in test_sorting_imports_and_standard_modules2
    self.import_tools.sort_imports(pymod))
AssertionError: 'import sys\nimport time\n' != u'import sys\n\nimport time\n'

**Comment by soupytwist** [comment]
Hi,
Can you please post the value of `sys.builtin_module_names`? Rope expects 'time' to be in this list, not sure why it would be different on your distribution.

https://docs.python.org/2/library/sys.html#sys.builtin_module_names

**Comment by stratakis** [comment]
Our downstream (Fedora) configuration for Python 2 is building the time module as a shared library, so it is not included in sys.builtin_module_names:

` >>> import time` 
`  >>> time ` 
`  <module 'time' from '/usr/lib64/python2.7/lib-dynload/timemodule.so'>`

In Python 3 it's built-in:
` >>> import time` 
`  >>> time ` 
`  <module 'time' (built-in)>`

**Comment by mcepl** [comment]
We can check for existence of ``time.__file__``, couldn't we? That should exist only when the module is not built-in, shouldn't it?

**Comment by soupytwist** [comment]
Right now, I think that `stdmods.standard_modules()` is going to include `'timemodule'` instead of time, we assume the module name matches the name of the `.so` in lib-dynload. We could special-case this one perhaps, so that `timemodule.so` is treated as `time`. They aren't actually imported here curently, so reading `module.__file__` might slow down significantly if everything has to be imported.

https://github.com/python-rope/rope/blob/master/rope/base/stdmods.py#L50

**Comment by mcepl** [comment]
I didn't say **read** ``module.__file__``, I said **check** whether that attribute exists.

**Comment by soupytwist** [comment]
Sorry, I might be missing something. Is it possible to get a reference to the `time` module to check if it has this attribute without importing the module?

**Comment by mcepl** [comment]
You are not, I am missing part of my brain … yes, so we need to limit ourselves to ``sys.builtin_module_names``.

**Comment by soupytwist** [comment]
Hi, can you test #225 and confirm this fixes your issue?

Thank you

**Comment by mcepl** [comment]
@soupytwist  https://github.com/python-rope/rope/pull/225#issuecomment-342721329

**Comment by stratakis** [comment]
I can confirm that #225  fixes the issue on Fedora and the tests pass successfully.

**Comment by soupytwist** [comment]
Thank you both for testing!
