### ISSUE TITLE
Python 3 - "Getting Started" not in the list

### ISSUE THREAD

**Issue by xcodeburpx** [python-rope/rope#213]
Recently I got the error when upgrading python-rope in Python 3.6.1:
pip install rope
Collecting rope
  Using cached rope-0.10.6.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-vm9ocb7n/rope/setup.py", line 67, in <module>
        long_description=get_long_description(),
      File "/tmp/pip-build-vm9ocb7n/rope/setup.py", line 61, in get_long_description
        end = lines.index('Getting Started')
    ValueError: 'Getting Started' is not in list
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-vm9ocb7n/rope/

The probrem is `lines` list has byte strings so `index` function doesn't work correctly.
I did temporary fix:
`def get_long_description():
    lines = open('README.rst', 'rb').read().splitlines(False)
    for i,_ in enumerate(lines):
        lines[i] = lines[i].decode('utf-8')
    #for number, line in enumerate(lines):
    #    print(number,":",line)
    #print("Overview",lines.index(b'Getting Started'))
    end = lines.index('Getting Started')
    return '\n' + '\n'.join(lines[:end]) + '\n'`

Is it correct for right now?

**Comment by soupytwist** [comment]
My fault, sorry about that. Bad release.

I pushed a new version which seems to fix this for me. Please try with
0.10.7 (in pypi).

Please let me know if this works for you, and sorry for the trouble.

Nick

**Comment by xcodeburpx** [comment]
Yes I installed this successfully. 
Thank you for the quick reply!

**Comment by sblondon** [comment]
I think it could be closed, isn't it?
