### ISSUE TITLE
Missing support for async/await?

### ISSUE THREAD

**Issue by abingham** [python-rope/rope#215]
I'm having trouble making rope work with code that uses async and await. For example, with code like this
```python
def some_name():
    return 42

some_name()
```

I can run a rename factoring from `some_name` to `some_other_name`.

But if I do something like this like this:
```python
import asyncio

def some_name():
    return 42

loop = asyncio.get_event_loop()
loop.run_until_complete(some_name())
```

and try the same refactoring, I get a `RefactoringError`:
```
  File "/Users/abingham/.virtualenvs/traad/lib/python3.6/site-packages/rope/refactor/multiproject.py", line 26, in __call__
    self.addpath, project, *args, **kwds)
  File "/Users/abingham/.virtualenvs/traad/lib/python3.6/site-packages/rope/refactor/multiproject.py", line 42, in __init__
    self.refactoring(other, *args, **kwds))
  File "/Users/abingham/.virtualenvs/traad/lib/python3.6/site-packages/rope/refactor/rename.py", line 28, in __init__
    'Rename refactoring should be performed'
rope.base.exceptions.RefactoringError: Rename refactoring should be performed on resolvable python identifiers.
```

Should rope work with this code? Am I missing something?

(FWIW, I'm doing the refactoring through traad, but I don't see how that would interfere with rope's support for the language.)

**Comment by soupytwist** [comment]
Looks like you are right. It's not obvious whether this is related to async or not, although I'm not sure there is support for that either. I can take a look when I get a chance.

**Comment by abingham** [comment]
I'm happy to help if I can. Can you give me any ideas of where I might start?

**Comment by emacsway** [comment]
@abingham , try to debug this case using console line interface of rope.

**Comment by abingham** [comment]
You mean to try doing the refactoring from the REPL or something? I'll give that a shot.

**Comment by abingham** [comment]
It looks like you're just missing some methods from your AST walkers. The async additions add a few new AST nodes types like `AsyncFunctionDef`, `AsyncWith`, `AsyncFor`, etc., and rope needs to account for those when it scans the AST.

As an experiment, I copied `rope.base.pyobjectsdef._ScopeVisitor._FunctionDef` to `rope.base.pyobjectsdef._ScopeVisitor._AsyncFunctionDef`. When I used this with my failing async example, the rename refactoring seemed to work.

I don't know enough about rope to know if this is a complete solution (i.e. even assuming I added methods for the other new node types). But if this sounds about right, I'd be happy to put together a pull-request and we could start work from there. Let me know.

**Comment by emacsway** [comment]
@abingham , thank you. It's useful information.  Can you, please, write regression test for this case in a branch? Me ( or @sergeyglazyrindev ) would find a time for the fix.

**Comment by abingham** [comment]
@emacsway [Here you go](https://github.com/python-rope/rope/pull/217).

**Comment by emacsway** [comment]
@abingham , thank you.

**Comment by mcepl** [comment]
@abingham So, what is the status of this bug in 0.12.0?

**Comment by abingham** [comment]
@mcepl I haven't done anything with this beyond the PRs I submitted. However, on quick inspection it looks like this issue can be closed. The tests in 0.12.0 include a number of renaming tests involving async keywords, and none of them seem to be failing.

So as far as I'm concerned this can be closed; I leave it up to you to decide.

**Comment by mcepl** [comment]
Thank you.
