### ISSUE TITLE
Pip has newer version than github

### ISSUE THREAD

**Issue by dickreuter** [python-rope/rope#222]
How is it possible that when I install rope from pip I have a later version number than when I download the latest source code from github?

**Comment by soupytwist** [comment]
Fixed in 7108c52c6cf00b6fe68e5f94c3bbabcca69183a8

I must have missed this file when bumping the version last time, so the change made it to pypi but not here. Thanks for raising the issue, it is fixed now. The code in pypi and on master are identical.
