### ISSUE TITLE
Support f"literal {string} interpolation" (PEP-498, Python 3.6)

### ISSUE THREAD

**Issue by Dominik-K** [python-rope/rope#226]
Seems like `rope` does not yet support rename variables in [literal string interpolations (PEP-498)](https://www.python.org/dev/peps/pep-0498/)  (included since Python 3.6), e.g. renaming `var` in `f"this {var} is interpolated"`. Tested it with [VSCode's Python extension](https://github.com/Microsoft/vscode-python) which uses `rope` underneaths.

Simple test: Rename `abc`

```python
#!/usr/bin/env python3.6

abc = "hello"

print(f"{abc}")
```

**Comment by soupytwist** [comment]
You're right, this is not supported. Support for refactoring python3 code is incomplete.

**Comment by soupytwist** [comment]
Hm, sorry I missed your comment. Rope does use `ast` to some extent, I don't know if there is any historical reason why it's not used move heavily.

**Comment by mcepl** [comment]
For history I would ask @aligrudi , but generally I am all for using as much standard library as possible.

**Comment by orn688** [comment]
@soupytwist @mcepl Ok, thanks! I'll go ahead and submit a PR with my changes just in case.
