### ISSUE TITLE
rename ignores code in locally defined functions

### ISSUE THREAD

**Issue by rwst** [python-rope/rope#232]
Renaming a class name worked only inside functions that are not nested.

**Comment by soupytwist** [comment]
Hmm, interesting. It's likely that rope isn't be sure that the references are correct. Do you have some sample code to reproduce it?

Thanks

**Comment by rwst** [comment]
Ah no, I seem to have other problems using rope, and misinterpreted so this is invalid. Let me investigate.

**Comment by rwst** [comment]
I found out why a specific rename only worked in the original file: I'm a Python noob and didn't give the exact project root as argument to `Project` so the imports in other files were ignored.
