### ISSUE TITLE
Rope doesnt seem to understand fixture names

### ISSUE THREAD

**Issue by alphaCTzo7G** [python-rope/rope#238]
I am using the rope included in `python-mode`. While refactoring a fixture name, I noticed that it doesnt see that it doesnt understand fixture names, atlease for the rope library included in `python-mode`: https://github.com/python-mode/python-mode

Does the current rope version understand fixture names, and can it correctly rename fixture names?

**Comment by soupytwist** [comment]
Sorry, I don't know what you mean by this. What is an example of a fixture name that is not correctly renamed? What happens vs what is expected?

**Comment by mcepl** [comment]
@alphaCTzo7G Are we talking about [pytest fixtures](https://docs.pytest.org/en/latest/fixture.html) here?

**Comment by mcepl** [comment]
Almost three years.
