### ISSUE TITLE
get_definition_location() goes to wrong instance

### ISSUE THREAD

**Issue by shaolo1** [python-rope/rope#248]
```
def foo(self):
    a = 0
    p = 'foo'''  # The extra single quote pair at the end is what breaks things!..without them it works as expected


def bar(self):
    a = 1
    a += 1  # using get_definition_location() on the a in this line will report line 2 vs 6
```

**Comment by shaolo1** [comment]
It is an odd case, but p = 'foo''bar' is valid python3 making p== 'foobar'.  This actually works with get_definition_location(), so it looks like its just the special case where the second string is empty that breaks things.

**Comment by soupytwist** [comment]
Very weird... sorry for the non-response, I don't have a good idea what the fix for this will entail. If you have the time to look into it, it would be appreciated, otherwise I will revisit when I have more time.

**Comment by shaolo1** [comment]
I "fixed" the extra quotes in my code, so get_definition_location() is working again for me, but I wanted to make sure the issue was logged in case someone else hit it.
