### ISSUE TITLE
Refactor-renames often fail iff numpydoc is installed

### ISSUE THREAD

**Issue by mawright** [python-rope/rope#253]
This issue has been noticed by some users of visual studio code which uses rope for its refactoring (eg https://github.com/Microsoft/vscode-python/issues/500).

With this example py file,
```python
class MyClass():
    def __init__(self, A):
        self.A = A

    def bb(self, b):
        self.b = b
        pass

    def CC(self):
        pass
```
Trying to refactor `b` gives a lengthy error stacktrace that exits rope at this line: https://github.com/python-rope/rope/blob/18a204c65109b50083d57f611e7090d3cfe7b761/rope/base/oi/type_hinting/providers/numpydocstrings.py#L20

The remainder of the stacktrace is (e.g.),
```('/home/matt/anaconda3/envs/test2/lib/python2.7/site-packages/numpydoc/docscrape.py', 138, '__init__', "docstring = textwrap.dedent(docstring).split('\\n')")

('/home/matt/anaconda3/envs/test2/lib/python2.7/textwrap.py', 390, 'dedent', "text = _whitespace_only_re.sub('', text)")
```

with the exception message being `expected string or buffer` in Python 2.7 and `expected string or bytes-like object` in Python 3.5 and 3.6 (these are the versions I tested).

So the issue is with the calls rope sends to numpydoc, or maybe some further-upstream issue with numpydoc itself.

But note that in the rope file we have the lines https://github.com/python-rope/rope/blob/18a204c65109b50083d57f611e7090d3cfe7b761/rope/base/oi/type_hinting/providers/numpydocstrings.py#L10-L13 that mean hitting the failing line of code is contingent on numpydoc being importable.

If numpydoc is not installed, the above refactor works as requested.

**Comment by soupytwist** [comment]
Thanks for reporting. It's a weird one. Thanks for digging into it already! I'll take a look as well.

**Comment by soupytwist** [comment]
@mawright I pushed a fix for this issue in 1e75468. Would you be able to verify the fix before I make a release? Thanks again!

**Comment by mawright** [comment]
Yep, seems to have fixed it for me!

**Comment by mawright** [comment]
I wonder if it is worth changing the return statement in your patch from `return None` to `return []` to be consistent with https://github.com/python-rope/rope/blob/1e75468d357e42c58df8f237ed01f7efd7d167f1/rope/base/oi/type_hinting/providers/numpydocstrings.py#L34 and https://github.com/python-rope/rope/blob/1e75468d357e42c58df8f237ed01f7efd7d167f1/rope/base/oi/type_hinting/providers/numpydocstrings.py#L39

**Comment by soupytwist** [comment]
Yes, that's what I meant to do... thanks for being observant!

**Comment by danhper** [comment]
Is there any chance we could get a release with this fix please?
Thank you very much!
