### ISSUE TITLE
rope fails to parse PEP 526 annotations

### ISSUE THREAD

**Issue by azatoth** [python-rope/rope#254]
[PEP 526](https://www.python.org/dev/peps/pep-0526/) variable annotations is available in python 3.6 and starts to get used in the wild, for example [Pydantic](https://github.com/samuelcolvin/pydantic) uses it as a core feature.

I'm using rope via [python-model](https://github.com/python-mode/python-mode) and off course made sure it's updated to latest.

```
 Traceback (most recent call last):
  File "/home/azatoth/.vim/bundle/python-mode/pymode/libs/rope/base/pyobjectsdef.py", line 189, in _init_source
    ast_node = ast.parse(source_bytes, filename=filename)
  File "/home/azatoth/.vim/bundle/python-mode/pymode/libs/rope/base/ast.py", line 21, in parse
    return compile(source, filename, 'exec', _ast.PyCF_ONLY_AST)
  File "import.py", line 31
    id: str
      ^
SyntaxError: invalid syntax       
```

Example code:

```python
from datetime import date
from pydantic import BaseModel
from typing import Optional


class FooModel(BaseModel):

    id: str
    start: Optional[date]
    end: Optional[date]


myfoo = FooModel(id='urn:gagaga', end='2018-08-18')

print(myfoo)
# FooModel id='urn:gagaga' start=None end=datetime.date(2018, 8, 18)
```

**Comment by soupytwist** [comment]
Thank you for the details. Rope hasn't yet had any support for 3.5+ including PEP-0484, and supporting this in rope is no small task.

Your report looks like rope is executing in a python<3.6 environment, however. Rope internally uses `ast.compile`, and this is failing with a `SyntaxError`. I believe if you were able to run rope in 3.6+ it may not fail outright, but would miss the type inference on these annotations.

**Comment by azatoth** [comment]
@soupytwist Ah, you are right, I'm actually running rope under python3.5, I wonder why that fact never clicked in my head

**Comment by soupytwist** [comment]
Great, Sergey! Good to see you here again.

**Comment by dmerejkowsky** [comment]
Looks like this is fixed :)

**Comment by mcepl** [comment]
Thank you.
