### ISSUE TITLE
Rename result

### ISSUE THREAD

**Issue by danielnowakowski** [python-rope/rope#256]
Is there any way to find out what changes are performed by rename? It should be nice to list it like:

file1, line1, col1
file2, line2, col2

**Comment by soupytwist** [comment]
Sort of... you can work it out from the `rope.base.change.ChangeSet`, each `ChangeContents` has a `resource` and `old_contents`/`new_contents`. From that, it shouldn't be too difficult to find which lines would be modified in a file.
