### ISSUE TITLE
Detecting module/package name changes.

### ISSUE THREAD

**Issue by iogf** [python-rope/rope#274]
It would be interesting to have Change.old_module_path/Change.old_package_path attributes when module/package are renamed. 

It is awkward to detect when modules had their names changed under a general case.

**Comment by soupytwist** [comment]
I'm not sure I understand. As it stands now, after the changes are applied, the `Change` instances are not meaningful anymore. Before applying the changes, you can find the old and new path at `MoveResource.resource.real_path` and `MoveResource.new_resource.real_path`

**Comment by iogf** [comment]
I figured that out. Thank you.
