### ISSUE TITLE
RopeOmni: Non-ascii characters in docstrings trigger unicode error

### ISSUE THREAD

**Issue by mcepl** [python-rope/rope#28]
If there are non-ascii chars in a docstring you'll get a unicode error. jedi-vim seems to know how manipulate the unicode repr:
https://github.com/davidhalter/jedi-vim/blob/master/plugin/jedi_vim.py#L16

(I'm using rope in the context of vim python mode and it appears to be up to date
https://github.com/klen/python-mode)

**Comment by soupytwist** [comment]
Closing as obsolete.
