### ISSUE TITLE
Renaming messes up a variable name

### ISSUE THREAD

**Issue by bersbersbers** [python-rope/rope#291]
I am using VS Code for refactoring Python code, and I assume this uses `rope`, so excuse if I am not in the right place here.

I start with this code:
```
out_dir = ""
for _ in []:
    out_dir / f""
    out_dir / ""
```

I then rename `out_dir` to `OUT_DIR`, and this is what I am left with:
```
OUT_DIR = ""
for _ in []:
    OUT_DIR / f""
    oOUT_DIRut_dir / ""
```

**Comment by lieryan** [comment]
Can't replicate in python 3.8.5/rope 0.18.0; are you still having issue with this? Also, please provide the python and rope version you're using.

**Comment by bersbersbers** [comment]
I'd like to try, but I am not getting any variable renaming to work in VS Code as of right now, both for "Jedi" (which uses `rope`) as well as "Pylance" (which does not, I believe). I'll get back to you.

**Comment by bersbersbers** [comment]
> Can't replicate in python 3.8.5/rope 0.18.0; are you still having issue with this? Also, please provide the python and rope version you're using.

I am now still able to repro this with `0.16.0` installed. This is an even easier example:
```
ab = f""
ab + ""
```

Renaming `ab` to `c` yields
```
c = f""
acb + ""
```

This issue appears only with `0.16.0` - not with `0.14.0`, nor `0.17.0`, nor `0.18.0`. But maybe it's a valuable test case to add.

**Comment by lieryan** [comment]
Closing as this issue is already fixed in latest version of rope. If you still have this issue and you're already using latest version of rope, please reopen a new ticket.
