### ISSUE TITLE
`Worder.get_primary_at` cuts off names that start like keywords.

### ISSUE THREAD

**Issue by thekrampus** [python-rope/rope#296]
Calling `Worder.get_primary_at` on code with names that start with Python keywords (but are otherwise valid names) gives bad results when given an offset exactly one character before the end of the part of the name that looks like a keyword.

For example:

```python
>>> from rope.base.worder import Worder
>>> Worder("is_keyword = False\n").get_primary_at(1)
's_keyword'
>>> Worder("global_valid_name = 10\n").get_primary_at(5)
'l_valid_name'
```

which is obviously not right.

This causes a number of strange issues with other `rope` tools that use `Worder`.

**Comment by lieryan** [comment]
Closing. This seems to no longer be an issue in latest rope.
