### ISSUE TITLE
type_hinting_test.py fails with python 3.9

### ISSUE THREAD

**Issue by nonamedotc** [python-rope/rope#300]
When compiled with python 3.9, type_hinting_test fails with

```self.assert_completion_in_result('is_alive', 'attribute', result)```

Patch to fix this issue from downstream bug report [1] is attached.

[isalive_fix_patch.txt](https://github.com/python-rope/rope/files/4726785/isalive_fix_patch.txt)

[0] https://bugzilla.redhat.com/show_bug.cgi?id=1834187#c6

**Comment by mattst88** [comment]
I believe this was fixed by f8d2428275286faf2acf9b5757859026963f851b and can be closed.

**Comment by mattst88** [comment]
@mcepl: I believe this is already fixed. Please close.

**Comment by mcepl** [comment]
Thank you for letting me know.
