### ISSUE TITLE
Unknown tokens in py3.7

### ISSUE THREAD

**Issue by bbcVld** [python-rope/rope#312]
When I run rope on my project I got some warnings:
```

.../patchedast.py:85: RuntimeWarning: Unknown node type <JoinedStr>; please report!
  % node.__class__.__name__, RuntimeWarning)
.../patchedast.py:85: RuntimeWarning: Unknown node type <AnnAssign>; please report!
  % node.__class__.__name__, RuntimeWarning)
.../patchedast.py:85: RuntimeWarning: Unknown node type <AsyncFunctionDef>; please report!
  % node.__class__.__name__, RuntimeWarning)
```
- [x] `<JoinedStr>` - it's f-string (`f'Some text {param}'`)
- [x] `<AsyncFunctionDef>` - it's async defenition (`async def func(): ...`) - example in iss #311 
- [x] `<AnnAssign>` - it's annotation to the variable (`a: str = None`), not function parameter.

versions:
```
 python --version
Python 3.7.6

pip show rope
Name: rope
Version: 0.18.0
```

**Comment by lieryan** [comment]
Hi thanks for reporting this. All of these will have already been fixed in master and will be part of the next upcoming release (rope==0.20.0).

- <JoinedStr> implemented in b37572b48
- <AsyncFunctionDev> implemented in 291ad2b9d
- <AnnAssign> implemented in 4871928f3
