### ISSUE TITLE
Refactor failed. 'NoneType' object has no attribute '_fields'

### ISSUE THREAD

**Issue by bg-bi** [python-rope/rope#317]
I'm using VSCode with rope 0.14.0 and trying to do a simple refactor to rename a local variable. I'm using a docker container as well.

Refactor failed. 'NoneType' object has no attribute '_fields'
[
<FrameSummary file /home/developer/.vscode-server/extensions/ms-python.python-2020.9.114305/pythonFiles/refactor.py, line 380 in watch>, 
<FrameSummary file /home/developer/.vscode-server/extensions/ms-python.python-2020.9.114305/pythonFiles/refactor.py, line 350 in _process_request>, 
<FrameSummary file /home/developer/.vscode-server/extensions/ms-python.python-2020.9.114305/pythonFiles/refactor.py, line 259 in _rename>, 
<FrameSummary file /home/developer/.vscode-server/extensions/ms-python.python-2020.9.114305/pythonFiles/refactor.py, line 128 in refactor>, 
<FrameSummary file /home/developer/.vscode-server/extensions/ms-python.python-2020.9.114305/pythonFiles/refactor.py, line 156 in onRefactor>, 
<FrameSummary file /usr/local/lib/python3.7/site-packages/rope/refactor/rename.py, line 101 in get_changes>, 
<FrameSummary file /usr/local/lib/python3.7/site-packages/rope/refactor/rename.py, line 117 in _is_renaming_a_module>, 
<FrameSummary file /usr/local/lib/python3.7/site-packages/rope/base/pynamesdef.py, line 22 in get_object>, 
<FrameSummary file /usr/local/lib/python3.7/site-packages/rope/base/utils/__init__.py, line 29 in newfunc>, 
<FrameSummary file /usr/local/lib/python3.7/site-packages/rope/base/pynames.py, line 188 in get>, 
<FrameSummary file /usr/local/lib/python3.7/site-packages/rope/base/utils/__init__.py, line 29 in newfunc>, 
<FrameSummary file /usr/local/lib/python3.7/site-packages/rope/base/pynamesdef.py, line 19 in _get_inferred>, 
<FrameSummary file /usr/local/lib/python3.7/site-packages/rope/base/utils/__init__.py, line 41 in newfunc>, 
<FrameSummary file /usr/local/lib/python3.7/site-packages/rope/base/oi/soi.py, line 71 in infer_assigned_object>, 
<FrameSummary file /usr/local/lib/python3.7/site-packages/rope/base/utils/__init__.py, line 41 in newfunc>, 
<FrameSummary file /usr/local/lib/python3.7/site-packages/rope/base/oi/soi.py, line 142 in _infer_assignment>, 
<FrameSummary file /usr/local/lib/python3.7/site-packages/rope/base/utils/__init__.py, line 41 in newfunc>, 
<FrameSummary file /usr/local/lib/python3.7/site-packages/rope/base/oi/soi.py, line 175 in _follow_pyname>, 
<FrameSummary file /usr/local/lib/python3.7/site-packages/rope/base/evaluate.py, line 27 in eval_node>, 
<FrameSummary file /usr/local/lib/python3.7/site-packages/rope/base/evaluate.py, line 32 in eval_node2>, 
<FrameSummary file /usr/local/lib/python3.7/site-packages/rope/base/ast.py, line 39 in walk>, 
<FrameSummary file /usr/local/lib/python3.7/site-packages/rope/base/evaluate.py, line 189 in _Call>, 
<FrameSummary file /usr/local/lib/python3.7/site-packages/rope/base/evaluate.py, line 170 in _get_returned>, 
<FrameSummary file /usr/local/lib/python3.7/site-packages/rope/base/builtins.py, line 108 in get_returned_object>, 
<FrameSummary file /usr/local/lib/python3.7/site-packages/rope/base/builtins.py, line 766 in _zip_function>, 
<FrameSummary file /usr/local/lib/python3.7/site-packages/rope/base/builtins.py, line 704 in _infer_sequence_for_pyname>, 
<FrameSummary file /usr/local/lib/python3.7/site-packages/rope/base/pynamesdef.py, line 22 in get_object>, 
<FrameSummary file /usr/local/lib/python3.7/site-packages/rope/base/utils/__init__.py, line 29 in newfunc>, 
<FrameSummary file /usr/local/lib/python3.7/site-packages/rope/base/pynames.py, line 188 in get>, 
<FrameSummary file /usr/local/lib/python3.7/site-packages/rope/base/utils/__init__.py, line 29 in newfunc>, 
<FrameSummary file /usr/local/lib/python3.7/site-packages/rope/base/pynamesdef.py, line 19 in _get_inferred>, 
<FrameSummary file /usr/local/lib/python3.7/site-packages/rope/base/utils/__init__.py, line 41 in newfunc>, 
<FrameSummary file /usr/local/lib/python3.7/site-packages/rope/base/oi/soi.py, line 71 in infer_assigned_object>, 
<FrameSummary file /usr/local/lib/python3.7/site-packages/rope/base/utils/__init__.py, line 41 in newfunc>, 
<FrameSummary file /usr/local/lib/python3.7/site-packages/rope/base/oi/soi.py, line 142 in _infer_assignment>, 
<FrameSummary file /usr/local/lib/python3.7/site-packages/rope/base/utils/__init__.py, line 41 in newfunc>, 
<FrameSummary file /usr/local/lib/python3.7/site-packages/rope/base/oi/soi.py, line 175 in _follow_pyname>, 
<FrameSummary file /usr/local/lib/python3.7/site-packages/rope/base/evaluate.py, line 27 in eval_node>, 
<FrameSummary file /usr/local/lib/python3.7/site-packages/rope/base/evaluate.py, line 32 in eval_node2>, 
<FrameSummary file /usr/local/lib/python3.7/site-packages/rope/base/ast.py, line 39 in walk>, 
<FrameSummary file /usr/local/lib/python3.7/site-packages/rope/base/evaluate.py, line 241 in _ListComp>, 
<FrameSummary file /usr/local/lib/python3.7/site-packages/rope/base/evaluate.py, line 252 in _what_does_comprehension_hold>, 
<FrameSummary file /usr/local/lib/python3.7/site-packages/rope/base/evaluate.py, line 27 in eval_node>, 
<FrameSummary file /usr/local/lib/python3.7/site-packages/rope/base/evaluate.py, line 32 in eval_node2>, 
<FrameSummary file /usr/local/lib/python3.7/site-packages/rope/base/ast.py, line 39 in walk>, 
<FrameSummary file /usr/local/lib/python3.7/site-packages/rope/base/evaluate.py, line 228 in _Dict>, 
<FrameSummary file /usr/local/lib/python3.7/site-packages/rope/base/evaluate.py, line 277 in _get_object_for_node>, 
<FrameSummary file /usr/local/lib/python3.7/site-packages/rope/base/evaluate.py, line 27 in eval_node>, 
<FrameSummary file /usr/local/lib/python3.7/site-packages/rope/base/evaluate.py, line 32 in eval_node2>, 
<FrameSummary file /usr/local/lib/python3.7/site-packages/rope/base/ast.py, line 40 in walk>, 
<FrameSummary file /usr/local/lib/python3.7/site-packages/rope/base/ast.py, line 48 in get_child_nodes>]

**Edit:**

Code sample that causes the error:

```python
gary = {**{'stuff': 'can'}, **{'stuff': 'crayon'}}

if "stuff" in gary:
    print("ya")
```

**Comment by lieryan** [comment]
Can you provide a minimal reproducible example? Without an example code, there isn't really anything anyone can do about this ticket.

**Comment by bg-bi** [comment]
Apologies.

```python
gary = {**{'stuff': 'can'}, **{'stuff': 'crayon'}}

if "stuff" in gary:
    print("ya")
```

This fails with the same message. I narrowed it down to a dictionary merge, which I think causes the error.
