### ISSUE TITLE
Long time taking to refactor

### ISSUE THREAD

**Issue by XtremeGood** [python-rope/rope#324]
I don't know but it takes too long to refactor on my win 10 , 64 bit, i7 7th gen , 16 GB RAM laptop.

![image](https://user-images.githubusercontent.com/40588378/102024714-acaa0600-3db9-11eb-8745-5f50bc619410.png)

**Comment by mcepl** [comment]
If you are using VS Code plugin, I am not completely persuaded they actually use this version of rope, or they bundled some of older (and probably even patched) version.

**Comment by XtremeGood** [comment]
Well I ‘m using vscode but it did a pip install in the virtualenv. Sent from Mail for Windows 10 From: Matěj CeplSent: 14 December 2020 06:15To: python-rope/ropeCc: Vishesh Mangla; AuthorSubject: Re: [python-rope/rope] Long time taking to refactor (#324) If you are using VS Code plugin, I am not completely persuaded they actually use this version of rope, or they bundled some of older (and probably even patched) version.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by zevaverbach** [comment]
Chiming in here with a +1. I'm on a modern Mac (2019 16" MBP) using VSCode, and the "rename" refactor takes ages to run.

**Comment by mcepl** [comment]
@zevaverbach , @XtremeGood could you both quantify “ages” and “too long”, please? Are we talking about seconds, minutes?

**Comment by zevaverbach** [comment]
@mcepl many seconds, upwards of 20-30.

**Comment by mcepl** [comment]
@zevaverbach And what size of the project? How many files, how many megabytes?

**Comment by XtremeGood** [comment]
just a single file of 30-40 lines

**Comment by lieryan** [comment]
> just a single file of 30-40 lines

That doesn't sound like a performance issue with rope, but rather how you development environment is set up. I've used rename refactor on really big Python projects, like 200kloc projects, and rename never takes more than two seconds to complete.

I am not familiar with VScode, but I noticed you might have a venv folder on your directory. Try moving your virtualenv folder to somewhere outside the rope project folder and see if you're still having an issue.

**Comment by mcepl** [comment]
I cannot reproduce here. Renaming with neovim+python-language-server (which uses rope for refactoring) takes a second or two, but nothing too crazy (and LSP itself adds substantial overhead).

**Comment by euseanwoon2016** [comment]
I also have this issue but I found that adding 'venv' to ` prefs['ignored_resources']` in `.vscode/.ropeproject/config.py` solves the issue.

**Comment by mcepl** [comment]
@XtremeGood does @euseanwoon2016 's workaround help for you? Should we make this default value of `.ropeproject/config.py`?

**Comment by XtremeGood** [comment]
Hi, it works now. It worked great after one of the updates in VS code.

**Comment by euseanwoon2016** [comment]
> 
> 
> @XtremeGood does @euseanwoon2016 's workaround help for you? Should we make this default value of `.ropeproject/config.py`?

I'm new to python so I can't really say. However, if venv is used frequently I'd believe that it should be a default value.

**Comment by mcepl** [comment]
@XtremeGood OK, I will do nothing for now, and write it up as some mysterious bug which has been resolved on the way (ours or VS Code).
