### ISSUE TITLE
Rope generates an error when spelling errors in quotes or comments are corrected

### ISSUE THREAD

**Issue by rjzupkoii** [python-rope/rope#338]
Issue found when correcting a spelling error in quotes or comments using the [Code Spell Checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker) extension (Version 1.10.2) in Visual Studio Code (Version 1.55.0) and Python extension (Version 2021.3.680753044). This issue may be related to #249 since the error generated is similar.

**Reproduction**
1. Create a new Python file
2. Enter a comment or string with a spelling error:

```python
# Spelling error: vlaue
test = 'Spelling error: vlaue'
``` 

3. Use Code Spell Checker to correct the spelling errors (i.e., select "Value" from the list)
4. Error appears in lower right corner of screen (see below)

**Expected Behavior**
Correcting a spelling error in a comment or string should not trigger a notice from Rope.

**Error Generated**
```
Refactor failed. Rename refactoring should be performed on resolvable python identifiers. [
<FrameSummary file c:\Users\NAME\.vscode\extensions\ms-python.python-2021.3.680753044\pythonFiles\refactor.py, line 380 in watch>, 
<FrameSummary file c:\Users\NAME\.vscode\extensions\ms-python.python-2021.3.680753044\pythonFiles\refactor.py, line 346 in _process_request>, 
<FrameSummary file c:\Users\NAME\.vscode\extensions\ms-python.python-2021.3.680753044\pythonFiles\refactor.py, line 259 in _rename>, 
<FrameSummary file c:\Users\NAME\.vscode\extensions\ms-python.python-2021.3.680753044\pythonFiles\refactor.py, line 128 in refactor>, 
<FrameSummary file c:\Users\NAME\.vscode\extensions\ms-python.python-2021.3.680753044\pythonFiles\refactor.py, line 155 in onRefactor>, 
<FrameSummary file C:\Users\NAME\AppData\Roaming\Python\Python38\site-packages\rope\refactor\rename.py, line 27 in __init__>]
```

**Comment by mcepl** [comment]
I don't see here anything testable and I am not persuaded that the bug is really in rope and not in the VSCode integration. Could I get full backtrace (not just names of functions) as well?

**Comment by rjzupkoii** [comment]
@mcepl Where / how can I generated the full back trace?

**Comment by mcepl** [comment]
I have no idea, I don't use VS Code. File the bug report there. If their developers think that the bug lies in rope, they will know how to provide relevant information.

**Comment by rjzupkoii** [comment]
@mcepl With a big of digging I as able to find the trigger for the variable is the rename provider in VS Code, if anyone uses the Code Spell Checker extension setting `cSpell.fixSpellingWithRenameProvider` to `false` seems to prevent this.

**Comment by mcepl** [comment]
Thank you. #249 have at least clear reproducer.
