### ISSUE TITLE
Feature Request: Do not define a variable if it is immediately returned

### ISSUE THREAD

**Issue by tbrodbeck** [python-rope/rope#355]
Hi it would be great if this could be enhanced:
# Actual:
```python
  [...]
  df = df.append(row, ignore_index=True)
  return df
```
# Shorter version:
```python
  [...]
  return df.append(row, ignore_index=True)
```
I regard this shorter, better readable and understandable

**Comment by mcepl** [comment]
Except, sometime it makes sense (when you plan to log `df` variable in future). Anyway, this is just a personal preference, not a bug, and unless you have a code to share, I won't keep this ticket open.

**Comment by tbrodbeck** [comment]
> Except, sometime it makes sense (when you plan to log `df` variable in future). Anyway, this is just a personal preference, not a bug, and unless you have a code to share, I won't keep this ticket open.

Sure if the variable would be logged or anything would be done with it, it should not be shortened and that is super:
```
  [...]
  df = df.append(row, ignore_index=True)
  logging.info(df)
  return df
```

But in most cases this will not happen. And I would prefer a shorter form (that can be still easily extended when you decide to log something afterwards etc.)

**Comment by mcepl** [comment]
As I said: Show me the Code™, and I will reopen the ticket.

**Comment by tbrodbeck** [comment]
You mean like a MWE?

Ok lets take this example function:
```python
def exampleFun(a, b, c, d):
  state1 = 69
  state2 = state1 + a
  state3 = state2 * b
  state4 = state3 - c
  return state4 / d
```

If I now extract the lines with state2, 3 and 4:
```python
def exampleFun(a, b, c, d):
  state1 = 69
  state4 = getState4(state1, a, b, c)
  return state4 / d

def getState4(state1, a, b, c):
  state2 = state1 + a
  state3 = state2 * b
  state4 = state3 - c
  return state4
```

What I think would be more precise (shorter and state4 is not declared at to points in the code):
```python
def exampleFun(a, b, c, d):
  state1 = 69
  state4 = getState4(state1, a, b, c)
  return state4 / d

def getState4(state1, a, b, c):
  state2 = state1 + a
  state3 = state2 * b
  return state3 - c
```

**Comment by mcepl** [comment]
No I meant https://lkml.org/lkml/2000/8/25/132 … if you want this functionality added, push here the pull request. There is no real maintainer of this project: just me collecting tickets and pull requests and making sure that not everything goes completely belly up.

**Comment by tbrodbeck** [comment]
Okay then I am just a little bit confused by this procedure. When you mean by code a solution to the problem: Normally an issue is open when there is no code/solution and closed when there is code. Here it seems to be the other way round. ^^
