### ISSUE TITLE
Provide support of python's Pathlib in setup.py and other packages

### ISSUE THREAD

**Issue by acharles7** [python-rope/rope#359]
Currently, `setup.py` uses `io` and `os.path` for file system manipulation which can be easily replaced with`Pathlib` makes setup.py look even nicer.

Would love to work on this issue!

**Comment by mcepl** [comment]
Show me the code!

**Comment by acharles7** [comment]
Just saw, `rope` has partial support of python3. Not sure which exact python3 version. If we are planning to use `Pathlib` then it comes with >= python 3.4

**Comment by lieryan** [comment]
Closing. Outdated, setup.py no longer exist.
