### ISSUE TITLE
ExtractMethod into a staticmethod/classmethod

### ISSUE THREAD

**Issue by lieryan** [python-rope/rope#371]
User Story: I want to extract a block of code into classmethod/staticmethod rather than into regular method. Background: https://github.com/python-rope/rope/issues/302#issuecomment-914592269

- ExtractMethod.get_changes() need to have an option to extract a block of code from a regular method into a staticmethod/classmethod.

Additional acceptance criteria:

- [x] update documentation

**Comment by climbus** [comment]
I can get this if it is free.

We have to establish an API.  get_changes is used to extracting methods and variables. 
With method extracting we have options: instance, class and static.
With variable extracting it will be local, instance, class (global has other option)

So we can add "type" argument with name of extracting type: get_changes(..., type="static") and validate it in child class. 
Other option is to add attrs for all purposes: get_changes(..., static=True) but this is a bad idea, I think.
Third option is overload get_changes method with different arguments. This is often considered as bad practice.

**Comment by lieryan** [comment]
> So we can add "type" argument with name of extracting type: get_changes(..., type="static") and validate it in child class.

This sounds like a sensible API to me, except that I would name `type` to be something else. In a codebase like rope that does a lot with type analysis, it'd get confusing to use `type` to refer to this. 

Another option to consider is if something like `get_changes(..., decorators=[ExtractMethod.CLASSMETHOD])` would be sensible. This might open the API up too much into territory that we are not ready to handle though.

Another alternative I've been thinking is to hijack the `extracted_name` parameter to pass special names that rope would interpret as requesting that the extracted method be a classmethod/staticmethod/property. For example:

- `get_changes(extracted_name="@my_new_function")` could be interpreted as create a classmethod named `my_new_function`
- `get_changes(extracted_name="$my_new_function")` could be interpreted as create a staticmethod named `my_new_function`

... and so on. The advantage of hijacking `extracted_name` for these purpose is that all existing editor integrations will be able to use this new feature without having to be modified, as users can just type the special prefix symbols to trigger these special behaviors.
