### ISSUE TITLE
Document build and release process

### ISSUE THREAD

**Issue by lieryan** [python-rope/rope#388]
Later down the road we want to be able to automate releases, but for now, let's document the existing process first.

**Comment by mcepl** [comment]
I want to complete disentangle myself from rope, so I may try to be around from a while to help with the transition, but less I do happier I am.

Concerning the release process, there is not much to be said:

1. Increase the number in `rope/__init__.py`
2. Tag the release with the tag annotation containing the release information
3. `python3 setup.py sdist`
4. twine upload -s dist/rope-$VERSION.tar.gz*

**Comment by lieryan** [comment]
Thanks for clarifying your intent. I think the next step in the transition is for me to set up and gain the credentials so I would be able to upload a new release to PyPI. 

Would you be able to add my PyPI account ([lieryan](https://pypi.org/user/lieryan/)) so I would be able to upload new releases for rope-related projects in PyPI?

And thank you again for all the years you've been maintaining rope.

**Comment by mcepl** [comment]
Done

**Comment by lieryan** [comment]
Thanks!

**Comment by lieryan** [comment]
Basic release process documentation now added in https://github.com/python-rope/rope/blob/620ff09bdd38777fb42460cec5514a861bb426f9/docs/release-process.rst
