### ISSUE TITLE
_self_name_in_body should inspect the AST rather than just textually-searching in the text

### ISSUE THREAD

**Issue by lieryan** [python-rope/rope#390]
We'll want _self_name_in_body to inspect the AST rather than just textually-searching in the text. Hint: look into the `self.info_collector`.

_Originally posted by @lieryan in https://github.com/python-rope/rope/pull/377#discussion_r706227473_

**Comment by climbus** [comment]
i've removed self_name_in_body. I think we can close it ;)

**Comment by lieryan** [comment]
Fixed in #377
