### ISSUE TITLE
Reformat code with black and add check on push

### ISSUE THREAD

**Issue by climbus** [python-rope/rope#399]
Can We reformat code with black?

I've checked on my fork and looks that everything is ok. Of course We must have cleat situation with branches and merging.

https://github.com/climbus/rope/actions/runs/1250987372

**Comment by lieryan** [comment]
Hi @climbus, 

Thanks for bringing this up. I wasn't able to use your branch as-is, so I've re-ran black and made a new commit instead. I have git attribute you as the commit author when making the [commit](https://github.com/python-rope/rope/pull/404/commits/ae87aa32c4e1f7d0b6680ebd977c5579e217361e) to credit you for bringing this topic up and for doing the original blackening. I hope you don't mind.
