### ISSUE TITLE
Migrate setup.py metadata to setup.cfg

### ISSUE THREAD

**Issue by lieryan** [python-rope/rope#413]

**Comment by lieryan** [comment]
Currently, setuptools does not support putting most project metadata in `pyproject.toml`. It still only supports reading metadata from `setup.cfg`. So this is not possible right now.

Changing the scope of this ticket to move metadata into `setup.cfg` instead.

**Comment by lieryan** [comment]
It seem like [`build`](https://pypa-build.readthedocs.io/en/latest/index.html) might allow us to do away with setuptools/setup.py entirely, so doing a full pyproject.toml might actually be possible here.

**Comment by bageljrkhanofemus** [comment]
This issue can be closed #473

**Comment by lieryan** [comment]
Thanks @bageljrkhanofemus. We're now already building using `build` for some time. With the pyproject.toml migration, this is no longer necessary.
