### ISSUE TITLE
Failed test_get_package_tuple_compiled: AttributeError: module 'zlib' has no attribute '__file__'

### ISSUE THREAD

**Issue by hosiet** [python-rope/rope#495]
**Describe the bug**
When building `rope` package, test `test_get_package_tuple_compiled` fails on my system due to unrelated error (assertion on `zlib` module).

**To Reproduce**

After cloning the GitHub project, execute the following commands in the source dir:

```
python3 setup.py config
python3 setup.py build
python3 -m pytest
```

The following error will occur:
```
==================================== ERRORS ====================================
______________ ERROR at setup of test_get_package_tuple_compiled _______________

    @pytest.fixture
    def zlib_path():
        import zlib
    
>       yield pathlib.Path(zlib.__file__)
E       AttributeError: module 'zlib' has no attribute '__file__'

ropetest/contrib/autoimport/conftest.py:58: AttributeError
```

I am not sure why the test assumes that `zlib.__file__` should exist:

```
% python3
Python 3.10.5 (main, Jun  8 2022, 09:26:22) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import zlib
>>> zlib.__file__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'zlib' has no attribute '__file__'. Did you mean: '__name__'?
>>> zlib
<module 'zlib' (built-in)>
>>>
```

**Editor information (please complete the following information):**
 - OS version: Debian Unstable/Sid
 - Python version: 3.10.5
 - Rope version: 1.2.0

**Comment by eivindjahren** [comment]
The fixtures seems to only be used with the following test:

https://github.com/python-rope/rope/blob/9ecc3ec3a918bdddfe0957de1e954181388def7d/ropetest/contrib/autoimport/utilstest.py#L59-L63

The intention of the test seems to check that the autoimporter can get the info of a package with `source.STANDARD` and `PackageType.COMPILED`, hence the use of zlib. However, on my system, `zlib` is actually a builtin so this test fails in two ways. So I suggest the following:

```python
@pytest.mark.skipif("zlib" in sys.builtin_module_names, reason=(
    "On som systems, zlib is a builtin package"
    " rather than a standard package."
)
@pytest.mark.skipif(platform == "win32", reason="Windows doesn't have compiled modules")
def test_get_package_tuple_compiled(zlib_path):
    assert Package(
        "zlib", Source.STANDARD, zlib_path, PackageType.COMPILED
    ) == utils.get_package_tuple(zlib_path)
```
This should fix the issue
