### ISSUE TITLE
history.py misuses "change"

### ISSUE THREAD

**Issue by edreamleo** [python-rope/rope#541]
pyflakes rightly issues the following two complaints:
```console
history.py:100:13: import 'change' from line 1 shadowed by loop variable
history.py:213:13: import 'change' from line 1 shadowed by loop variable
```
The top level defines 'change' as follows:
```python
from rope.base import exceptions, change, taskhandle
```
`History._move_front` is:
```python
def _move_front(self, change_list, changes):
    for change in changes:
        change_list.remove(change)
        change_list.append(change)
```
`_FindChangeDependencies.__init__` defines self.change this way:
```python
def __init__(self, change_list):
    self.change = change_list[0]
    self.change_list = change_list
    self.changed_resources = set(self.change.get_changed_resources())
```
`_FindChangeDependencies.__call__` is:
```python
def __call__(self):
    result = [self.change]
    for change in self.change_list[1:]:
        if self._depends_on(change, result):
            result.append(change)
            self.changed_resources.update(change.get_changed_resources())
    return result
```
It *might*  be valid to rename 'change' to (say) 'changed' in `History._move_front`, but the code in
`__call__` is particularly dubious. Note the call to change.get_changed_resources, which presumably is meant to refer to the top-level imported 'change' var.

I don't fully trust the unit tests to properly test any revised code. Any additional eyeballs on the code would be appreciated.

**Comment by lieryan** [comment]
The `get_changed_resources()` is defined in the [Change and ChangeSet classes](https://github.com/python-rope/rope/blob/5939ed64b529ddb728cc4b0001482a0008e6b23a/rope/base/change.py#L112). 

So the `change.get_changed_resources()` line in `__call__` doesn't refer to the top level import, but rather to the Change object that is the content of change_list.

IOW, renaming those should be valid refactoring. I wouldn't rename them to `changes` though, as that would be plurals and I would expect variables whose names are plural to be container types, not singular object. If you annotate the loop variable, it should be ok to rename `change` to `ch: Change`, as the type information no longer need to be carried by the variable name.

**Comment by edreamleo** [comment]
@lieryan Thanks for your insights. `ch: Change` seems like a needed annotation.

**Comment by edreamleo** [comment]
@lieryan I'll issue a PR with your suggested change later today or tomorrow, unless you want to do the work yourself.
