### ISSUE TITLE
Automatically purge autoimport.db when there is schema change 

### ISSUE THREAD

**Issue by lieryan** [python-rope/rope#565]
**Is your feature request related to a problem? Please describe.**

Currently, rope/contrib/autoimport/sqlite.py creates an sqlite database at autoimport.db that caches the result of scanning `site-packages` for names that are useful during autoimport.

Currently, when you upgrade rope version and the database schema has changed, it doesn't have any way to know that it should purge the database and do a re-scan.

**Describe the solution you'd like**

- [x] `version_hash` should be calculated from `rope.VERSION`, a hash of `rope/contrib/autoimport/models.py` file, and a hash of user preferences. (#631)
- [x] create a new `metadata` table, this table should contain a single column named `version_hash`
- [x] if the `version_hash` changes, then the database should be considered outdated and autoimport should re-scan the environment

**Additional context**

- #516 and #515 depends on this mechanism

**Comment by bagel897** [comment]
Can we also version the config so we can handle updates to settings like underlined?

**Comment by lieryan** [comment]
@bagel897 thanks, that's a very good point. I've added it to the ticket.
