### ISSUE TITLE
Eliminate the confusing import in pyobjectsdef.py

### ISSUE THREAD

**Issue by edreamleo** [python-rope/rope#569]
In pyobjectsdef.py:

- [x] Replace:
```python
from rope.base import (
    pynamesdef as pynames,
    ...
```
with:
```python
from rope.base import (
    pynamesdef,
    ...
```
- [x] Replace `pynames` with `pynamesdef` everywhere in pyobjectsdef.py.

The name `pynamesdef` appears nowhere else in pyobjectsdef.py, so the proposed renaming is safe.

**Comment by lieryan** [comment]
+1, yes, this should be done

**Comment by edreamleo** [comment]
@lieryan Thanks!
