### ISSUE TITLE
Retire `perform_doa`/`doi` inference?

### ISSUE THREAD

**Issue by edreamleo** [python-rope/rope#571]
@lieryan said that few if any Rope uses seem to be using dynamic inference.

It so, removing the doi code might suggest other simplifications.

In turn, those simplifications might help the proposed aoi inference, #568.

@lieryan Your comments, please.

**Comment by lieryan** [comment]
Note that I don't actually have any actual numbers on how many people are using doi. For all I know, this could have been a setting that basically everyone but me flipped to on as soon as they install rope. It's hard to work with deprecations when you don't have a ~~spyware~~ telemetry telling you how people are using the software 😅.

I'd be happy to see it go away if it's not used, but if there are any major users of doi, then speak now or forever hold your peace.

**Comment by edreamleo** [comment]
@lieryan How do you propose asking Rope's users about doi?

Are you assuming they are monitoring Rope's issues?

**Comment by lieryan** [comment]
> Are you assuming they are monitoring Rope's issues?

Most probably don't. There are probably many people using rope without even knowing it. They might just install some editor plugins and without ever digging deeper, it might not be immediately obvious to users that it uses rope.

> How do you propose asking Rope's users about doi?

I don't have answers to that. I've been thinking about maybe asking users in general Python communities (e.g. Reddit, HN, Discord, mailing list).

It would not be bad to have a social media/marketing-type people to run user research campaigns, though I don't know why those kind of people would be hanging around in a forum for refactoring library 😅

I'm proposing though to just do the scream test.

> "The Scream Test is simple - remove it and wait for the screams. If someone screams, put it back."

**Comment by edreamleo** [comment]
@lieryan Hehe. The scream test!
