### ISSUE TITLE
Replace rope.base.RopeNodeVisitor with stdlib.ast.NodeVisitor

### ISSUE THREAD

**Issue by edreamleo** [python-rope/rope#619]
`stdlib.ast.NodeVisitor.visit` calls the method called `self.visit_classname`, where classname is the name of the node class, or `generic_visit` if that method doesn’t exist.

`rope.base.ast.RopeNodeVisitor.visit` does the same thing, except that the names of the methods are `self._classname`. Note that `RopeNodeVisitor` already calls `stdlib.ast.NodeVisitor.generic_visit` when a visitor method doesn't exist.

So, if I understand correctly, the task list is:

- [ ] Rename all visitor methods, replacing `_` with `visit_`.
- [ ] Use (stdlib) `ast.NodeVisitor` as the base class of all of Rope's visitors.

**Comment by lieryan** [comment]
That's right, it's a fairly simple change, just somewhat tedious changes. Note that not all functions in RopeNodeVisitor are AST callbacks. There are some helper functions that are just called from other AST callbacks, but would never be called by visit/generic_visit.

**Comment by edreamleo** [comment]
@lieryan Thanks for your helpful comments.

**Comment by edreamleo** [comment]
I am going to close this issue. I have also closed PR #619.
