### ISSUE TITLE
Improve the docstring for the @saveit decorator

### ISSUE THREAD

**Issue by edreamleo** [python-rope/rope#644]
See PR #652.

I have spent many happy hours over the past two days studying the `@saveit` (aka `@cacheit`) decorator. [This Engineering Notebook page](https://github.com/python-rope/rope/wiki/ENB-4:-The-@saveit-(@cacheit)-decorator) records these investigations.

@lieryan I have become a fan of this decorator. It deserves an excellent docstring. Here is the first draft. Please suggest improvements!
```python
"""
A decorator that supports the `lazy singleton` pattern.

For each decorated function, the decorator creates the singleton value when
the decorated function is first called, *not* when importing a module.

The decorator injects a `private helper ivar` (name) into `self`.
Only the decorator uses this ivar.

:param func: A function/method that instantiates an object.
    
:return: getattr(self, name), the singleton value computed by func.
"""
```
The ENB makes several suggestions:

`@singleton` seems like a better name than either `@saveit` or `@cacheit`.
This decorator involves startup code, not type inference.

`f"_singleton_{func.__name__}.replace('__', '_')` might be a better name for the private helper ivar.

A *separate* `@factory` decorator would be a good idea if `func` returns a factory (Callable).
The docstrings for `@factory` and `@singleton` would be different, as would their annotations.

@lieryan I would appreciate any guidance or comments about this issue or the ENB.

**Comment by lieryan** [comment]
`@saveit` is basically just a version of the same idea as what modern python now has `@functools.cache/cached_property` in the standard library. `@saveit` was devised back when `functools.cache/cached_property` didn't exist.

I think most (all?) instances of `saveit` could just be replaced with `functools.cached_property`. Note that `@cached_property` was added in Python 3.8, so we still have at least a couple months until we can reliably use it in supported versions of Python. My plan was originally to wait it out until Python 3.7 is EOL before deprecating `saveit`, but if you want to do this now, you'll want to backport the functools decorators.

Note that there are also some code of rope that currently manually implements the caching pattern currently done by `saveit`. Most of these could probably be turned into `@cached_property` as well (e.g. [_ResourceMatcher.compiled_patterns](https://github.com/python-rope/rope/blob/d24294fd4f410c72340d98ae8127855549f93192/rope/base/resources.py#L263-L269) and [_ExtractInfo](https://github.com/python-rope/rope/blob/d24294fd4f410c72340d98ae8127855549f93192/rope/refactor/extract.py#L227-L265), there may be others).

**Comment by edreamleo** [comment]
@lieryan Many thanks for your comments. I agree: there is no big reason to rename `@saveit`. I'll rename this issue instead :-)

I'd like to include references to `functools.cache` and `functools.cached_property` in the docstring. What do you think?

**Comment by edreamleo** [comment]
@lieryan I'm busy with Leo for at least a few more days. I'll attend to this PR when the dust settles.

**Comment by edreamleo** [comment]
@lieryan Still working through Leo issues. I hope to rejoin you in about a week, but you know how those estimates are...

**Comment by edreamleo** [comment]
@lieryan Thanks for your understanding. The dreaded software (and website) rot needs periodic attention.
