### ISSUE TITLE
Relative auto-imports

### ISSUE THREAD

**Issue by lieryan** [python-rope/rope#683]
### Discussed in https://github.com/python-rope/rope/discussions/682

<div type='discussions-op-text'>

<sup>Originally posted by **jaycle** March  8, 2023</sup>
Hi, I'm using rope through python-lsp-server and neovim.

My question is if it is possible to control how the auto import functionality builds the import statement? My `:LspInfo` puts my root directory at the top of my project. But I have separate python projects (and other languages) in directories beneath.

Auto-import works great, but it builds a path like `from server.app.models import MyModel` when within, say, `server/app/views.py` (typical Django project structure).</div>

<div type='discussions-op-text'>

<sup>Originally posted by **lieryan**</sup>
The current implementation of autoimport supports only absolute import. It should be possible to implement a setting to do relative import though this is not currently implemented yet, here is the place where [rope generate the import statement](https://github.com/python-rope/rope/blob/7e1c8971a42bfe0414f914b456ce242e2bea10a6/rope/contrib/autoimport/sqlite.py#L200-L204).

For relative import, python-lsp-server would also need to pass in the filename of the importing module, so that would require a change in both rope and python-lsp-server.</div>

**Comment by bagel897** [comment]
> I am personally against relative imports, especially for autoimport. For autoimport there's additional difficulty in generating these suggestions. Besides the argument passing, you'd need to find imports relative to each other with the filenames. I did not design the parsing or utils modules to handle relative imports. Currently, they do not put filenames into the database. Part of this is that some modules are imported (i.e.: They used the compiled path) and probably cannot be used for relative imports. Furthermore, it'd be confusing for the user to have two suggestions per completion.
>
> If someone wanted to implement this, they'd be welcome to, the relevant parts are both _search_name and _search_module. I'd hide it behind a config flag which changes the default for completions in the project from absolute to relative.
> 
>This is a rope issue, it'd first have to be implemented here.

From the discussion

**Comment by lieryan** [comment]
Agreed with @bagel897 with all the points raised there that relative import is generally quite problematic under most circumstances. If we would ever support relative auto import, it would have to be disabled by default.

I think this can be implemented by changing the SearchResult class by adding a method that does what SearchResult.import_statement does, but takes an additional parameter, the importing_module. That likely wouldn't have require any changes in the indexing mechanism.

**Comment by bagel897** [comment]
You'd need to know the file location of the module that's being imported as well. This isn't put in the DB right now.

**Comment by lieryan** [comment]
I may not have thought all the corner cases very thoroughly, so I'm probably missing some obvious, but does the actual file location really matters? If the importing module is `a.b.c` and the imported module is `a.b.d`, wouldn't it be possible to just calculate a relative path by stripping the common prefix which is `a.b` so it's become `from .d import ...`?

Is there any situation where

**Comment by lieryan** [comment]
Closing this issue, the original requester turns out were having a completely different issue than what it originally appears to be. 

If anyone else needed a feature like this, then please re-open a new ticket.
