### ISSUE TITLE
Renaming methd

### ISSUE THREAD

**Issue by moenesbs** [python-rope/rope#695]
**Describe the bug**
I am trying to rename a method to a new target. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Code before refactoring:

```
class Compute:
    def a(self):
        return 5
    def b(self):
        return 6


def calcul():
    test = Compute()
    return test.a()
```

2. Describe the refactoring you want to do :
 I want to refactor test.a() to test.b()

I am using this code to refactor

```
file_offset = resource.read().index("test.a") # I tried also just writing a, or .a instead of test.a
refactor = Rename(project, resource, file_offset)
changes = refactor.get_changes("test.b")
```

3. Expected code after refactoring:

```
def calcul():
    test = Compute()
    return test.b()
```

4. Describe the error or unexpected result that you are getting
The `get_changes` is returning `Renaming <test> to <test.b> ` in this exemple

**Editor information (please complete the following information):**
 - Project Python version: 3.10
 - Rope Python version: 1.8.0

Could you please show me the correct way to do a rename for my use case.
Thank you

**Comment by lieryan** [comment]
The offset that you passed into Rename needs to point to `a` exactly. There are two places this can be:

1. You can point to the name in the definition:

    def a(self):
        
2. You can point to the name in the usage:

    return test.a()

Try this: `file_offset = resource.read().index("test.a") + len("test.")`

Or: `file_offset = resource.read().index("a(")`.

Rope is primarily designed to be used as a library for editors, so most of the refactorings uses file offsets to represent user's edit cursor.

If you're doing programmatic refactoring, and you need to have something a bit more robust than `str.index()` and a bunch of offset maths, you may need to use the ast to get the appropriate file offset, or there may be other libraries more appropriate for that kind of use case.
