### ISSUE TITLE
Rename refactoring allow the use of the same name of the declared method in the superclass

### ISSUE THREAD

**Issue by jonhnanthan** [python-rope/rope#699]
Rename refactoring is successfully executed using the name of the already declared method in the superclass.

1. Code before refactoring:

A.py:
```
class A:

    def k(self, a: int) -> int:
        return 10

```

B.py:
```
from A import A


class B(A):

    def n(self, a: int) -> int:
        return 20

```

2. Apply the Rename refactoring in the method B.n to B.k

3. Expected to Rope emit an error due to the existence of the method in the superclass.

**Comment by lieryan** [comment]
Hi @jonhnanthan thank you for taking the time to write this ticket. 

I don't think this behavior is a bug. If the user wanted to change B.n into an overload for function A.k, there should be no reason why the library should prevent the user from doing that. It's the user's responsibility to ensure that the target name makes sense for what they are doing.

I don't have any objections to adding a method that the frontend interface (editor/IDE) can call verify whether the destination name exists and is available, but ultimately I think that validation should be optional and it should be up to the frontend interface to decide how the UI would appear and to warn the user when renaming to a destination name that already exists.
