### ISSUE TITLE
rope incompatible with Python 3.12

### ISSUE THREAD

**Issue by detlevo** [python-rope/rope#708]
I tested rope with Python 3.12 (rc3) and have to let you know, that it is not compatible. For example, the 'Extract Method' function does not work because ast.Str does not exist anymore. There are other places like this for sure, but that particular one is the one, I stumbled over. This test was done via the ['eric-ide'](https.//eric-ide.python-projects.org) integrated development environment.

Detlev

**Comment by lieryan** [comment]
Thanks for testing rope with 3.12. rope follows the release schedule for Python, so 3.12 is currently not officially supported yet. 

I'm going to start work on fixing issues with 3.12 since it will be released next month.

**Comment by lieryan** [comment]
Python 3.12 support is added on #709 and will be part of rope 1.10 release.
