### ISSUE TITLE
autoimport does not correctly use index

### ISSUE THREAD

**Issue by lieryan** [python-rope/rope#736]
**Describe the bug**

Related conversation: 

- https://github.com/python-rope/rope/pull/730/files#r1385746802

@MrBago made an IPython notebook testing the performance of an unrelated query. This brings up an unrelated performance issue with the search_by_module_like and likely the other like queries as well.

A prefix search using an index should not have been that slow. Indeed, it doesn't seem to be correctly using the index as `EXPLAIN QUERY PLAN` shows that it is doing a full table scan on the LIKE query so the index doesn't seem to be defined correctly, I think this is because of a [case sensitivity](https://stackoverflow.com/questions/8584499/should-like-searchstr-use-an-index) issue on the index.

**To Reproduce**

```
In [78]: %time _ = list(autoimport._execute(m.Name.search_module_like.select_star(), ["abc"]))
```

**Comment by tkrabel-db** [comment]
@lieryan are there any updates on this issue? Do you have an ETA when you want to do this? I have capacity to work on this, so I am happy to help!
