### ISSUE TITLE
Rename Field refactoring allows the use of declared method names as new field names

### ISSUE THREAD

**Issue by jonhnanthan** [python-rope/rope#763]
Rename Field refactoring allows the use of declared method names as new field names
It would be nice if Rope emits an alert to the user and asks if want to continue the application, avoiding incompatible types

1. Code before refactoring:
```python
string_types = (str,)


def with_metaclass():
    pass

```

2. Apply the Rename Field refactoring using 'with_metaclass' as the new name for 'string_types'.

**Comment by lieryan** [comment]
Closing. Ticket merged into #779.
