### ISSUE TITLE
Rename Field refactoring allows you to rename a local field with the method name

### ISSUE THREAD

**Issue by jonhnanthan** [python-rope/rope#766]
Rename Field refactoring allows the use of the name of the recursive method in the field inside the same method.
It would be nice if Rope could emit an alert to the user to confirm the operation to avoid type errors

1. Code before refactoring:
```python
def pluralize(word, pos="NN", custom={}, classical=True):
    if word.endswith("'"):
        owners = pluralize(word.rstrip("'s"), pos, custom, classical)
        if owners.endswith("s"):
            return owners + "'"

    words = word.replace("-", " ").split(" ")
    return word.replace(words[0], pluralize(words[0], pos, custom, classical))

```
2. Apply the Rename Field refactoring with the new name 'pluralize' to the 'owners' field.

**Comment by lieryan** [comment]
Closing. Ticket merged into #779.
