### ISSUE TITLE
Rename Method refactoring allows the use of previously declared field name

### ISSUE THREAD

**Issue by jonhnanthan** [python-rope/rope#768]
Rename Method refactoring allows the use of previously declared field name
It would be nice if Rope sent an alert to the user to prevent incompatible variable types in the code

1. Steps to reproduce the behavior:

structure
>-- main
>---- formats.py
>-- test
>---- test.py

formats.py:
```python
DEFAULT_ENCODING = 'utf-8'


def detect(fp, max_read=1024):
    return None

```

test.py:
```python
import unittest

from main import formats

CSV_FILE = 'data.csv'


class TestFormats(unittest.TestCase):

    def test_detect_csv(self):
        with open(CSV_FILE) as fp:
            format = formats.detect(fp)
        assert_equal(format, ",")

```
2. Apply the Rename Method refactoring with the new name 'DEFAULT_ENCODING' to the method 'detect' in formats.py

**Comment by lieryan** [comment]
Closing. Ticket merged into #779.
